language: python
python:
  - "2.7"
# command to install dependencies
install:
  - python setup.py install
  - pip install httpretty==0.6.0
  - pip install coverage
  - pip install python-coveralls
# command to run tests
script:
  - coverage run --source=restnavigator/ setup.py test
after-success:
  - coveralls