language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install python-coveralls
  - pip install -U virtualenv py
  - pip install -e .[test]
# command to run tests
script:
  - tox
  - py.test --cov=restnavigator --cov-report=term-missing tests
after_success:
  - coveralls
